export const REGISTER_NEW_USER = "REGISTER_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const USER_EXIT = "USER_EXIT"
export const USER_NEW_NAME = "USER_NEW_NAME"
export const USER_NEW_MESS = "USER_NEW_MESS"
export const USER_DEL_MESS = "USER_DEL_MESS"
export const GET_CHAT = "GET_CHAT"